import {
  FieldMetadataType,
  RelationOnDeleteAction,
  RelationType,
} from 'arjuna-shared/types';

import { type FlatFieldMetadata } from 'src/engine/metadata-modules/flat-field-metadata/types/flat-field-metadata.type';
import { type AllStandardObjectFieldName } from 'src/engine/workspace-manager/arjuna-standard-application/types/all-standard-object-field-name.type';
import {
  type CreateStandardFieldArgs,
  createStandardFieldFlatMetadata,
} from 'src/engine/workspace-manager/arjuna-standard-application/utils/field-metadata/create-standard-field-flat-metadata.util';
import { createStandardRelationFieldFlatMetadata } from 'src/engine/workspace-manager/arjuna-standard-application/utils/field-metadata/create-standard-relation-field-flat-metadata.util';

export const buildMessageFolderStandardFlatFieldMetadatas = ({
  now,
  objectName,
  workspaceId,
  standardObjectMetadataRelatedEntityIds,
  dependencyFlatEntityMaps,
  arjunaStandardApplicationId,
}: Omit<CreateStandardFieldArgs<'messageFolder'>, 'context'>): Record<
  AllStandardObjectFieldName<'messageFolder'>,
  FlatFieldMetadata
> => ({
  id: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'id',
      type: FieldMetadataType.UUID,
      label: 'Id',
      description: 'Id',
      icon: 'Icon123',
      isSystem: true,
      isNullable: false,
      isUIReadOnly: true,
      defaultValue: 'uuid',
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    arjunaStandardApplicationId,
    now,
  }),
  createdAt: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'createdAt',
      type: FieldMetadataType.DATE_TIME,
      label: 'Creation date',
      description: 'Creation date',
      icon: 'IconCalendar',
      isNullable: false,
      isUIReadOnly: true,
      defaultValue: 'now',
      settings: { displayFormat: 'RELATIVE' },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    arjunaStandardApplicationId,
    now,
  }),
  updatedAt: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'updatedAt',
      type: FieldMetadataType.DATE_TIME,
      label: 'Last update',
      description: 'Last time the record was changed',
      icon: 'IconCalendarClock',
      isNullable: false,
      isUIReadOnly: true,
      defaultValue: 'now',
      settings: { displayFormat: 'RELATIVE' },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    arjunaStandardApplicationId,
    now,
  }),
  deletedAt: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'deletedAt',
      type: FieldMetadataType.DATE_TIME,
      label: 'Deleted at',
      description: 'Date when the record was deleted',
      icon: 'IconCalendarMinus',
      isNullable: true,
      isUIReadOnly: true,
      settings: { displayFormat: 'RELATIVE' },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    arjunaStandardApplicationId,
    now,
  }),
  name: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'name',
      type: FieldMetadataType.TEXT,
      label: 'Name',
      description: 'Folder name',
      icon: 'IconFolder',
      isNullable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    arjunaStandardApplicationId,
    now,
  }),
  syncCursor: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'syncCursor',
      type: FieldMetadataType.TEXT,
      label: 'Sync Cursor',
      description: 'Sync Cursor',
      icon: 'IconHash',
      isNullable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    arjunaStandardApplicationId,
    now,
  }),
  isSentFolder: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'isSentFolder',
      type: FieldMetadataType.BOOLEAN,
      label: 'Is Sent Folder',
      description: 'Is Sent Folder',
      icon: 'IconCheck',
      isNullable: false,
      defaultValue: false,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    arjunaStandardApplicationId,
    now,
  }),
  isSynced: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'isSynced',
      type: FieldMetadataType.BOOLEAN,
      label: 'Is Synced',
      description: 'Is Synced',
      icon: 'IconCheck',
      isNullable: false,
      defaultValue: false,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    arjunaStandardApplicationId,
    now,
  }),
  parentFolderId: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'parentFolderId',
      type: FieldMetadataType.TEXT,
      label: 'Parent Folder ID',
      description: 'Parent Folder ID',
      icon: 'IconFolder',
      isNullable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    arjunaStandardApplicationId,
    now,
  }),
  externalId: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'externalId',
      type: FieldMetadataType.TEXT,
      label: 'External ID',
      description: 'External ID',
      icon: 'IconHash',
      isNullable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    arjunaStandardApplicationId,
    now,
  }),
  pendingSyncAction: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'pendingSyncAction',
      type: FieldMetadataType.SELECT,
      label: 'Pending Sync Action',
      description: 'Pending action for folder sync',
      icon: 'IconReload',
      isNullable: false,
      defaultValue: "'NONE'",
      options: [
        {
          value: 'FOLDER_DELETION',
          label: 'Folder deletion',
          position: 0,
          color: 'red',
        },
        { value: 'NONE', label: 'None', position: 1, color: 'blue' },
      ],
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    arjunaStandardApplicationId,
    now,
  }),
  messageChannel: createStandardRelationFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'messageChannel',
      label: 'Message Channel',
      description: 'Message Channel',
      icon: 'IconMessage',
      isNullable: false,
      targetObjectName: 'messageChannel',
      targetFieldName: 'messageFolders',
      settings: {
        relationType: RelationType.MANY_TO_ONE,
        onDelete: RelationOnDeleteAction.CASCADE,
        joinColumnName: 'messageChannelId',
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    arjunaStandardApplicationId,
    now,
  }),
});
